/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hospital.h"

bool_t
xdr_str_t (XDR *xdrs, str_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_list (XDR *xdrs, list *objp)
{
	register int32_t *buf;

	 if (!xdr_LIST (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_arg (XDR *xdrs, arg *objp)
{
	register int32_t *buf;

	 if (!xdr_ARG (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_field (XDR *xdrs, field *objp)
{
	register int32_t *buf;

	 if (!xdr_FIELD (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FIELD (XDR *xdrs, FIELD *objp)
{
	register int32_t *buf;

	 if (!xdr_str_t (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_LIST (XDR *xdrs, LIST *objp)
{
	register int32_t *buf;

	 if (!xdr_field (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->age))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->gender))
		 return FALSE;
	 if (!xdr_field (xdrs, &objp->cause))
		 return FALSE;
	 if (!xdr_field (xdrs, &objp->unit))
		 return FALSE;
	 if (!xdr_field (xdrs, &objp->admission))
		 return FALSE;
	 if (!xdr_field (xdrs, &objp->discharge))
		 return FALSE;
	 if (!xdr_field (xdrs, &objp->doctor))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (list), (xdrproc_t) xdr_list))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ARG (XDR *xdrs, ARG *objp)
{
	register int32_t *buf;

	 if (!xdr_field (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->item, sizeof (list), (xdrproc_t) xdr_list))
		 return FALSE;
	return TRUE;
}
