/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HOSPITAL_H_RPCGEN
#define _HOSPITAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *str_t;

typedef struct LIST list;

typedef struct ARG arg;

typedef struct FIELD field;

struct FIELD {
	str_t data;
};
typedef struct FIELD FIELD;

struct LIST {
	field id;
	int age;
	bool_t gender;
	field cause;
	field unit;
	field admission;
	field discharge;
	field doctor;
	list *next;
};
typedef struct LIST LIST;

struct ARG {
	field id;
	list *item;
};
typedef struct ARG ARG;

#define DATABASEPROG 30000
#define DATABASEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DBOPEN 1
extern  int * dbopen_1(field *, CLIENT *);
extern  int * dbopen_1_svc(field *, struct svc_req *);
#define DBINSERT 2
extern  bool_t * dbinsert_1(list *, CLIENT *);
extern  bool_t * dbinsert_1_svc(list *, struct svc_req *);
#define DBQUERY 3
extern  list * dbquery_1(field *, CLIENT *);
extern  list * dbquery_1_svc(field *, struct svc_req *);
#define DBREMOVE 4
extern  bool_t * dbremove_1(field *, CLIENT *);
extern  bool_t * dbremove_1_svc(field *, struct svc_req *);
#define DBREPLACE 5
extern  bool_t * dbreplace_1(arg *, CLIENT *);
extern  bool_t * dbreplace_1_svc(arg *, struct svc_req *);
#define DBCLOSE 6
extern  bool_t * dbclose_1(field *, CLIENT *);
extern  bool_t * dbclose_1_svc(field *, struct svc_req *);
extern int databaseprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DBOPEN 1
extern  int * dbopen_1();
extern  int * dbopen_1_svc();
#define DBINSERT 2
extern  bool_t * dbinsert_1();
extern  bool_t * dbinsert_1_svc();
#define DBQUERY 3
extern  list * dbquery_1();
extern  list * dbquery_1_svc();
#define DBREMOVE 4
extern  bool_t * dbremove_1();
extern  bool_t * dbremove_1_svc();
#define DBREPLACE 5
extern  bool_t * dbreplace_1();
extern  bool_t * dbreplace_1_svc();
#define DBCLOSE 6
extern  bool_t * dbclose_1();
extern  bool_t * dbclose_1_svc();
extern int databaseprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str_t (XDR *, str_t*);
extern  bool_t xdr_list (XDR *, list*);
extern  bool_t xdr_arg (XDR *, arg*);
extern  bool_t xdr_field (XDR *, field*);
extern  bool_t xdr_FIELD (XDR *, FIELD*);
extern  bool_t xdr_LIST (XDR *, LIST*);
extern  bool_t xdr_ARG (XDR *, ARG*);

#else /* K&R C */
extern bool_t xdr_str_t ();
extern bool_t xdr_list ();
extern bool_t xdr_arg ();
extern bool_t xdr_field ();
extern bool_t xdr_FIELD ();
extern bool_t xdr_LIST ();
extern bool_t xdr_ARG ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HOSPITAL_H_RPCGEN */
